[package]
name = "rust-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[dev-dependencies]
criterion = "0.5.1"
smallvec = "*"
tinyvec = { version = "*", features = ["alloc"] }

[[bench]]
name = "vectors"
harness = false

